# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-13 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_products_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterModelTable(
            name='products',
            table='prod',
        ),
    ]
