# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-15 17:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_comments_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='phone',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.Phone'),
        ),
    ]
