# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-15 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_comments_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='image',
            field=models.ImageField(null=True, upload_to='/image'),
        ),
    ]
