# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-16 20:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0012_auto_20161115_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='creator',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comments',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='title',
            field=models.CharField(max_length=300),
        ),
    ]
