# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-18 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20161117_0326'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='quantity',
            field=models.IntegerField(default=10),
        ),
    ]
